# tcia_to_ml_classify — generated by `qr workflow scaffold --executor prefect`
# TCIA download → DICOM → outcome-prediction ML model (5 stages).
from pathlib import Path
from subprocess import run
from prefect import flow, task

PARAMS = {
    "cohort_root": "runs/lidc_idri/dicom",
    "clinical_csv": "lidc_idri/clinical/clinical.csv",
    "outdir": "runs/lidc_idri",
    "nrrd_dir": "runs/lidc_idri/nrrd",
    "roi": "Nodule",
    "pattern": "ct-default",
    "task": "classify",
    "outcome": "malignancy",
    "time_col": "OS_days",
    "event_col": "OS_event",
    "collection": "LIDC-IDRI",
    "modalities": "CT,RTSTRUCT",
    "max_series": 0,
}

def _format(value):
    """Substitute {var} placeholders in a string."""
    if isinstance(value, str):
        for k, v in PARAMS.items():
            value = value.replace('{' + k + '}', str(v))
    return value

@task
def t_tcia_series():
    cmd = ["qr", "tcia", "series", "--collection", _format("{collection}"), "--output", _format("{outdir}/series.csv")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_tcia_download():
    cmd = ["qr", "tcia", "download", "--manifest", _format("{outdir}/series.csv"), "--output", _format("{outdir}/dicom"), "--max-series", _format("{max_series}")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_manifest_dicom():
    cmd = ["qr", "convert", "manifest-from-dir", "--dataset-root", _format("{cohort_root}"), "--image-glob", _format("**/CT"), "--mask-glob", _format("**/RS.*.dcm"), "--output", _format("{outdir}/dicom_manifest.csv")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_convert_ct(patient_id: str):
    cmd = ["qr", "convert", "dicom-series", "--input", _format(f"{cohort_root}/{pid}/CT".replace("{pid}", patient_id)), "--output", _format(f"{nrrd_dir}/{pid}_CT.nrrd".replace("{pid}", patient_id))]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_convert_rt(patient_id: str):
    cmd = ["qr", "convert", "rtstruct", "--dicom-dir", _format(f"{cohort_root}/{pid}/CT".replace("{pid}", patient_id)), "--rtstruct", _format(f"{cohort_root}/{pid}/RTSeries/RS.dcm".replace("{pid}", patient_id)), "--roi", _format("{roi}"), "--output", _format(f"{nrrd_dir}/{pid}_{roi}-label.nrrd".replace("{pid}", patient_id))]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_manifest_nrrd():
    cmd = ["qr", "convert", "manifest-from-dir", "--dataset-root", _format("{nrrd_dir}"), "--image-glob", _format("*_CT.nrrd"), "--mask-glob", _format("*_{roi}-label.nrrd"), "--output", _format("{outdir}/manifest.csv")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_extract(patient_id: str):
    cmd = ["qr", "extract", "--manifest", _format("{outdir}/manifest.csv"), "--pattern", _format("{pattern}"), "--output", _format("{outdir}/features.csv")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_merge():
    cmd = ["qr", "results", "merge", "--features", _format("{outdir}/features.csv"), "--clinical", _format("{clinical_csv}"), "--clinical-id-col", _format("patient_id"), "--time-col", _format("{time_col}"), "--event-col", _format("{event_col}"), "--output", _format("{outdir}/analysis_ready.csv")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_train():
    cmd = ["qr", "ml", "train", "--input", _format("{outdir}/analysis_ready.csv"), "--task", _format("{task}"), "--outcome", _format("{outcome}"), "--model", _format("{outdir}/model.pkl"), "--metrics", _format("{outdir}/cv_metrics.json")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def t_evaluate():
    cmd = ["qr", "ml", "evaluate", "--input", _format("{outdir}/analysis_ready.csv"), "--model", _format("{outdir}/model.pkl"), "--task", _format("{task}"), "--outcome", _format("{outcome}"), "--report", _format("{outdir}/evaluation.json")]
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@flow
def workflow():
    cohort = Path(_format('{cohort_root}'))
    patients = sorted(p.name for p in cohort.iterdir() if p.is_dir())
    t_tcia_series()
    t_tcia_download()
    t_manifest_dicom()
    t_convert_ct.map(patients)
    t_convert_rt.map(patients)
    t_manifest_nrrd()
    t_extract.map(patients)
    t_merge()
    t_train()
    t_evaluate()

if __name__ == '__main__':
    workflow()