// tcia_to_ml_survival — generated by `qr workflow scaffold`
// TCIA download → DICOM → outcome-prediction ML model (5 stages).
nextflow.enable.dsl = 2

params.cohort_root = "runs/lung1/dicom"
params.clinical_csv = "lung1/clinical/clinical.csv"
params.outdir = "runs/lung1"
params.nrrd_dir = "runs/lung1/nrrd"
params.roi = "GTV-1"
params.pattern = "nsclc-survival"
params.task = "survival"
params.outcome = "OS_event"
params.time_col = "OS_days"
params.event_col = "OS_event"
params.collection = "NSCLC-Radiomics"
params.modalities = "CT,RTSTRUCT"
params.max_series = 0

process p_tcia_series {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr tcia series \
        --collection ${params.collection} \
        --output ${params.outdir}/series.csv
    """
}

process p_tcia_download {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr tcia download \
        --manifest ${params.outdir}/series.csv \
        --output ${params.outdir}/dicom \
        --max-series ${params.max_series}
    """
}

process p_manifest_dicom {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr convert manifest-from-dir \
        --dataset-root ${params.cohort_root} \
        --image-glob **/CT \
        --mask-glob **/RS.*.dcm \
        --output ${params.outdir}/dicom_manifest.csv
    """
}

process p_convert_ct {
    tag "$pid"
    input:
    tuple val(pid), val(_ready)
    output:
    tuple val(pid), val(true), emit: done

    script:
    """
    qr convert dicom-series \
        --input ${params.cohort_root}/${pid}/CT \
        --output ${params.nrrd_dir}/${pid}_CT.nrrd
    """
}

process p_convert_rt {
    tag "$pid"
    input:
    tuple val(pid), val(_ready)
    output:
    tuple val(pid), val(true), emit: done

    script:
    """
    qr convert rtstruct \
        --dicom-dir ${params.cohort_root}/${pid}/CT \
        --rtstruct ${params.cohort_root}/${pid}/RTSeries/RS.dcm \
        --roi ${params.roi} \
        --output ${params.nrrd_dir}/${pid}_${params.roi}-label.nrrd
    """
}

process p_manifest_nrrd {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr convert manifest-from-dir \
        --dataset-root ${params.nrrd_dir} \
        --image-glob *_CT.nrrd \
        --mask-glob *_${params.roi}-label.nrrd \
        --output ${params.outdir}/manifest.csv
    """
}

process p_extract {
    tag "$pid"
    input:
    tuple val(pid), val(_ready)
    output:
    tuple val(pid), val(true), emit: done

    script:
    """
    qr extract \
        --manifest ${params.outdir}/manifest.csv \
        --pattern ${params.pattern} \
        --output ${params.outdir}/features.csv
    """
}

process p_merge {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr results merge \
        --features ${params.outdir}/features.csv \
        --clinical ${params.clinical_csv} \
        --clinical-id-col patient_id \
        --time-col ${params.time_col} \
        --event-col ${params.event_col} \
        --output ${params.outdir}/analysis_ready.csv
    """
}

process p_train {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr ml train \
        --input ${params.outdir}/analysis_ready.csv \
        --task ${params.task} \
        --outcome ${params.outcome} \
        --model ${params.outdir}/model.pkl \
        --metrics ${params.outdir}/cv_metrics.json
    """
}

process p_evaluate {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr ml evaluate \
        --input ${params.outdir}/analysis_ready.csv \
        --model ${params.outdir}/model.pkl \
        --task ${params.task} \
        --outcome ${params.outcome} \
        --report ${params.outdir}/evaluation.json
    """
}

workflow {
    // Channel of patient IDs; emits once upstream has populated cohort_root
    patients = Channel.value(1).map { new File("${params.cohort_root}").listFiles().findAll { d -> d.isDirectory() }.collect { d -> d.name } }.flatten()
    ready = Channel.value(true)

    p_tcia_series(ready)
    p_tcia_download(p_tcia_series.out.done)
    p_manifest_dicom(p_tcia_download.out.done)
    p_convert_ct_in = patients.combine(p_manifest_dicom.out.done)
    p_convert_ct(p_convert_ct_in)
    p_convert_ct_done = p_convert_ct.out.done.collect().map { true }
    p_convert_rt_in = patients.combine(p_convert_ct_done)
    p_convert_rt(p_convert_rt_in)
    p_convert_rt_done = p_convert_rt.out.done.collect().map { true }
    p_manifest_nrrd(p_convert_rt_done)
    p_extract_in = patients.combine(p_manifest_nrrd.out.done)
    p_extract(p_extract_in)
    p_extract_done = p_extract.out.done.collect().map { true }
    p_merge(p_extract_done)
    p_train(p_merge.out.done)
    p_evaluate(p_train.out.done)
}