// tcia_to_ml_survival — generated by `qr workflow scaffold`
// TCIA → outcome-prediction ML model (8 steps, 4 canonical stages).
nextflow.enable.dsl = 2

params.outdir = "runs/lung1"
params.nrrd_dir = "runs/lung1/nrrd"
params.clinical_csv = "pipelines/lung1/clinical/clinical.csv"
params.collection = "NSCLC-Radiomics"
params.modalities = "CT,RTSTRUCT"
params.max_series = 0
params.roi = "GTV"
params.pattern = "nsclc-survival"
params.task = "survival"
params.outcome = "OS_event"
params.time_col = "OS_days"
params.event_col = "OS_event"

process p_tcia_series {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr tcia series \
        --collection ${params.collection} \
        --output ${params.outdir}/series.csv
    """
}

process p_tcia_download {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr tcia download \
        --manifest ${params.outdir}/series.csv \
        --output ${params.outdir}/dicom \
        --max-series ${params.max_series}
    """
}

process p_tcia_manifest {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr tcia manifest \
        --series ${params.outdir}/series.csv \
        --dicom-root ${params.outdir}/dicom \
        --output ${params.outdir}/dicom_manifest.csv
    """
}

process p_convert_from_manifest {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr convert from-manifest \
        --manifest ${params.outdir}/dicom_manifest.csv \
        --nrrd-dir ${params.nrrd_dir} \
        --roi ${params.roi} \
        --output ${params.outdir}/manifest.csv
    """
}

process p_extract {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr extract \
        --manifest ${params.outdir}/manifest.csv \
        --pattern ${params.pattern} \
        --output ${params.outdir}/features.csv
    """
}

process p_merge {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr results merge \
        --features ${params.outdir}/features.csv \
        --clinical ${params.clinical_csv} \
        --clinical-id-col patient_id \
        --time-col ${params.time_col} \
        --event-col ${params.event_col} \
        --output ${params.outdir}/analysis_ready.csv
    """
}

process p_train {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr ml train \
        --input ${params.outdir}/analysis_ready.csv \
        --task ${params.task} \
        --outcome ${params.outcome} \
        --model ${params.outdir}/model.pkl \
        --metrics ${params.outdir}/cv_metrics.json
    """
}

process p_evaluate {
    input:
    val(_ready)
    output:
    val(true), emit: done

    script:
    """
    qr ml evaluate \
        --input ${params.outdir}/analysis_ready.csv \
        --model ${params.outdir}/model.pkl \
        --task ${params.task} \
        --outcome ${params.outcome} \
        --report ${params.outdir}/evaluation.json
    """
}

def _list_patients() {
    def d = new File("${params.cohort_root}")
    return d.isDirectory()
        ? d.listFiles().findAll { f -> f.isDirectory() }.collect { f -> f.name }
        : []
}

workflow {
    ready = Channel.value(true)

    p_tcia_series(ready)
    p_tcia_download(p_tcia_series.out.done)
    p_tcia_manifest(p_tcia_download.out.done)
    p_convert_from_manifest(p_tcia_manifest.out.done)
    p_extract(p_convert_from_manifest.out.done)
    p_merge(p_extract.out.done)
    p_train(p_merge.out.done)
    p_evaluate(p_train.out.done)
}