# tcia_to_ml_survival — generated by `qr workflow scaffold --executor prefect`
# TCIA → outcome-prediction ML model (8 steps, 4 canonical stages).
#
# Coarse stage-level Prefect flow. One @task per pipeline stage; per-
# patient fan-out happens inside the task via a thread pool so the
# Prefect UI stays readable. Prefect tracks WHEN/WHERE; qr does WHAT.
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from subprocess import run
from prefect import flow, task

PARAMS = {
    "outdir": "runs/lung1",
    "nrrd_dir": "runs/lung1/nrrd",
    "clinical_csv": "pipelines/lung1/clinical/clinical.csv",
    "collection": "NSCLC-Radiomics",
    "modalities": "CT,RTSTRUCT",
    "max_series": 0,
    "roi": "GTV-1",
    "pattern": "nsclc-survival",
    "task": "survival",
    "outcome": "OS_event",
    "time_col": "OS_days",
    "event_col": "OS_event",
}

MAX_WORKERS = int(os.environ.get('QR_PREFECT_WORKERS', '4'))

def _format(value, pid=None):
    """Substitute {var} placeholders. {patient_id} → pid when given."""
    if isinstance(value, str):
        if pid is not None:
            value = value.replace('{patient_id}', pid)
        for k, v in PARAMS.items():
            value = value.replace('{' + k + '}', str(v))
    return value

def _patients():
    cohort = Path(_format('{cohort_root}'))
    if not cohort.is_dir():
        return []
    return sorted(p.name for p in cohort.iterdir() if p.is_dir())

def _register_artifacts(stage):
    """Attach canonical artifacts to the active Prefect run."""
    try:
        from prefect.artifacts import create_link_artifact
    except ImportError:
        return
    for path_tmpl in _STAGE_ARTIFACTS.get(stage, []):
        p = Path(_format(path_tmpl))
        if p.exists():
            try:
                # Path.as_uri() requires an absolute path; the plan vars use
                # relative paths (e.g. `runs/<cohort>/...`). Resolve against
                # the worker's CWD before turning into a file:// URI.
                create_link_artifact(
                    key=f'{stage}-{p.name.replace(".", "-")}',
                    link=p.resolve().as_uri(),
                    description=f'{stage} stage artifact: {p.name}',
                )
            except Exception:
                # Never let an observability hiccup kill a real stage.
                pass

_STAGE_ARTIFACTS = {
    "data": ['{outdir}/series.csv', '{outdir}/dicom_manifest.csv'],
    "image": ['{outdir}/manifest.csv'],
    "features": ['{outdir}/features.csv'],
    "modeling": ['{outdir}/analysis_ready.csv', '{outdir}/model.pkl', '{outdir}/cv_metrics.json', '{outdir}/evaluation.json'],
}

def _run_step(cmd_str, args, pid=None):
    """Run a single qr step. cmd_str is the qr verb chain; args is a dict."""
    cmd = ['qr'] + cmd_str.split()
    for k, v in args.items():
        cmd.append(f'--{k}')
        cmd.append(_format(str(v), pid=pid))
    Path(_format('{outdir}')).mkdir(parents=True, exist_ok=True)
    run(cmd, check=True)

@task
def stage_data():
    """Stage `data` — 3 step(s): tcia_series, tcia_download, tcia_manifest."""
    # Step `tcia_series`
    _run_step('tcia series', {"collection": '{collection}', "output": '{outdir}/series.csv'})
    # Step `tcia_download`
    _run_step('tcia download', {"manifest": '{outdir}/series.csv', "output": '{outdir}/dicom', "max-series": '{max_series}'})
    # Step `tcia_manifest`
    _run_step('tcia manifest', {"series": '{outdir}/series.csv', "dicom-root": '{outdir}/dicom', "output": '{outdir}/dicom_manifest.csv'})
    _register_artifacts("data")

@task
def stage_image():
    """Stage `image` — 1 step(s): convert_from_manifest."""
    # Step `convert_from_manifest`
    _run_step('convert from-manifest', {"manifest": '{outdir}/dicom_manifest.csv', "nrrd-dir": '{nrrd_dir}', "roi": '{roi}', "output": '{outdir}/manifest.csv'})
    _register_artifacts("image")

@task
def stage_features():
    """Stage `features` — 2 step(s): extract, merge."""
    # Step `extract`
    _run_step('extract', {"manifest": '{outdir}/manifest.csv', "pattern": '{pattern}', "output": '{outdir}/features.csv'})
    # Step `merge`
    _run_step('results merge', {"features": '{outdir}/features.csv', "clinical": '{clinical_csv}', "clinical-id-col": 'patient_id', "time-col": '{time_col}', "event-col": '{event_col}', "output": '{outdir}/analysis_ready.csv'})
    _register_artifacts("features")

@task
def stage_modeling():
    """Stage `modeling` — 2 step(s): train, evaluate."""
    # Step `train`
    _run_step('ml train', {"input": '{outdir}/analysis_ready.csv', "task": '{task}', "outcome": '{outcome}', "model": '{outdir}/model.pkl', "metrics": '{outdir}/cv_metrics.json'})
    # Step `evaluate`
    _run_step('ml evaluate', {"input": '{outdir}/analysis_ready.csv', "model": '{outdir}/model.pkl', "task": '{task}', "outcome": '{outcome}', "report": '{outdir}/evaluation.json'})
    _register_artifacts("modeling")

@flow(name='phase_a_features')
def phase_a_features():
    """Phase A — PACS/TCIA → features. Nextflow-suited, file-level fan-out."""
    stage_data()
    stage_image()
    stage_features()

@flow(name='phase_b_modeling')
def phase_b_modeling():
    """Phase B — analysis_ready.csv → trained model. MLflow-suited."""
    stage_modeling()

@flow(name='tcia_to_ml_survival')
def workflow():
    """Cohort entry point — wires Phase A → Phase B."""
    phase_a_features()
    phase_b_modeling()

if __name__ == '__main__':
    workflow()